CREATE TABLE   MERDM.BMCP_T99_MCC_CODE_INFO_P AS
   SELECT
        cast(ceil(T2.MCC_ID) as string)  AS MCC_LV2 ,
        T2.MCC_NAME AS MCC_NAME_LV2 ,
         cast(ceil(T1.MCC_ID) as string) AS MCC_LV1,
        T1.MCC_NAME AS MCC_NAME_LV1 ,
        cast(ceil(T0.MCC_ID) as string) AS MCC_LV0,
        T0.MCC_NAME AS MCC_NAME_LV0 ,
        ceil(T2.MCC_CODE) AS  MCC_CODE,
        T2.MEMO ,  T2.RATE_TYPE,
        T2.BASE_FEE_RATE,
        T2.BASE_COST_RATE,
        T2.MAX_FEE,
        T2.MAX_COST,
        T2.MCC_FIR,
        T2.MCC_SEC,
        T2.STATUS,
        T2.MCC_KIND
   FROM
  (SELECT * FROM  HDS.BMCP_T99_MCC_CODE_INFO   WHERE MCC_LEVEL =2 AND STATUS= 'VALID'  ) T2
  LEFT JOIN
   (SELECT * FROM  HDS.BMCP_T99_MCC_CODE_INFO   WHERE MCC_LEVEL =1 AND STATUS= 'VALID' ) T1
  ON T2.PARENT_MCC = T1.MCC_ID
  LEFT JOIN
    (SELECT * FROM  HDS.BMCP_T99_MCC_CODE_INFO   WHERE MCC_LEVEL =0 AND STATUS= 'VALID' ) T0
  ON T1.PARENT_MCC = T0.MCC_ID   ;
